In [1]:
"""Pyhton ile istatiksel analizler yapmamızı sağlayan kütüphanedir."""


'Pyhton ile istatiksel analizler yapmamızı sağlayan kütüphanedir.'

In [2]:
#1)numpy.array ile Liste veya tuple'dan Array oluşturma
import numpy as np

#Bir listeyi numpy array'e dönüştürelim
arr=np.array([10,20,30,40,50])
print(arr)

#Tuple'dan array oluşturma
arr_tuple=np.array((10,20,30,40,50))
print(arr_tuple)


[10 20 30 40 50]
[10 20 30 40 50]


In [3]:
#numpy.zeros ile Sıfırlarla dolu array oluşturma

#1D sıfırlarla dolu bir array
zero_array=np.zeros(10)
print(zero_array)

#2D sıfırlarla dolu bir array
zero_array2=np.zeros((3,4))
print(zero_array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#numpy.ones ile dolu bir array
ones_array=np.ones(10)
print(ones_array)

ones_array2=np.ones((3,4))
print(ones_array2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#numpy.random ile rastgele sayılarla

rand_arr=np.random.rand(10)
print(rand_arr)

rand_arr2=np.random.rand(3,4)
print(rand_arr2)





[0.46810686 0.56765585 0.77593571 0.11795426 0.06041849 0.72008674
 0.66572104 0.66574479 0.08001303 0.18331278]
[[0.62617734 0.47630673 0.75755741 0.00444989]
 [0.02644439 0.64010887 0.22444814 0.65010265]
 [0.2653233  0.24151636 0.17895872 0.02713918]]


In [6]:
#numpy.full ile sabit degerli array
const_arr=np.full((3,4),5)
print(const_arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
#1-Yeniden Şekillendirme(Reshaping)

#Orjinal aray 1D'li

arr=np.array([10,20,30,40,50,60])


#2D array dönüştürme
reshaped=arr.reshape(2,3)
print(reshaped)

[[10 20 30]
 [40 50 60]]


In [9]:
#Birleştirme(Concatenation)

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

#Birleştirme
arr3=np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [10]:
"""
Temel İstatiksel Ölçümler
"""

'\nTemel İstatiksel Ölçümler\n'

In [11]:
data=np.array([13,45,67,87,56,45])

#Ortalama
mean_value=np.mean(data)
print("Ortalama:",mean_value)

Ortalama: 52.166666666666664


In [12]:
#Medyan:Bir dizinin ortanca değerini alır
median_value=np.median(data)
print("Medyan:",median_value)

Medyan: 50.5


In [13]:
#Standart Sapma
std_sp=np.std(data)
print("Standart Sapma:",std_sp)

Standart Sapma: 22.674630953752892


In [14]:
#Varyans
variance=np.var(data)
print("Varyans:",variance)

Varyans: 514.1388888888888


In [15]:
#Min-Max değerleri ile bulalım
min_value=np.min(data)
max_value=np.max(data)
print("Min Değer:",min_value)
print("Max Değer:",max_value)

Min Değer: 13
Max Değer: 87
